### ISSUE TITLE
[bug] dualformer backbone is not in __init__.py

### ISSUE THREAD

**Issue by bishop986** [sail-sg/dualformer#1]
https://github.com/sail-sg/dualformer/blob/de0cdf858ca71a388ea006034cabcfa2e30fa33a/mmaction/models/__init__.py#L1

**Comment by CastleLiang** [comment]
Hi, thank you for raising this issue. 

DualFormer has already been imported [here](https://github.com/sail-sg/dualformer/blob/main/mmaction/models/backbones/__init__.py#L5)
