### ISSUE TITLE
Missing .md files

### ISSUE THREAD

**Issue by asif-hanif** [sail-sg/dualformer#2]
Hi @yoshall 
Thank you for your work.
I have noticed that a few .md files in the repo have broken links (at the time of writing of this issue)  e.g. [install.md](https://github.com/open-mmlab/mmaction2/blob/master/docs/en/install.md), [data_preparation.md](https://github.com/open-mmlab/mmaction2/blob/master/docs/en/data_preparation.md) and  [supported_datasets.md](https://github.com/open-mmlab/mmaction2/tree/master/docs/en/supported_datasets.md)

Could you please fix these links?

**Comment by CastleLiang** [comment]
Hi Asif, you can find the md files at 
https://github.com/open-mmlab/mmaction2/blob/master/docs/data_preparation.md
https://github.com/open-mmlab/mmaction2/tree/master/docs/supported_datasets.md
